CREATE OR REPLACE EDITIONABLE TRIGGER TRG_EMPLEADOS_UPPER
BEFORE INSERT OR UPDATE ON oratest9_dev.empleados
FOR EACH ROW
BEGIN
  :NEW.nombre := UPPER(:NEW.nombre);
  :NEW.apellido := UPPER(:NEW.apellido);
END;

/
ALTER TRIGGER TRG_EMPLEADOS_UPPER ENABLE;

